export const CITY_CHANGE = "CITY_CHANGE";
export const METRIC_CHANGE = "METRIC_CHANGE";
export const GET_WEATHER = "GET_WEATHER";
export const GET_WEATHER_START = "GET_WEATHER_START";
export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
export const GET_WEATHER_FAIL = "GET_WEATHER_FAIL";
